create_clock -period 16.000 -name fe_clk -waveform {0.000 8.000} [get_nets fe_clk]
create_clock -period 10.000 -name usb_clk -waveform {0.000 5.000} [get_nets usb_clk]
#create_clock -period  4.000 -name trigger_clk -waveform {0.000 2.000} [get_nets trigger_clk]
# NOTE: above would warn of overwriting automatically declared clock; instead, set alias for simplicity:
create_generated_clock -name trigger_clk [get_pins U_trigger_clock/inst/mmcm_adv_inst/CLKOUT0]

# TODO: temporary? could be dangerous to leave this in:
set_false_path -from [get_clocks usb_clk] -to [get_clocks trigger_clk]
#set_false_path -from [get_clocks usb_clk] -to [get_clocks clk_out1_clk_wiz_0]

set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN A10 [get_ports {fe_data[1]}]
set_property PACKAGE_PIN A12 [get_ports fe_dppd]
set_property PACKAGE_PIN A13 [get_ports fe_rxerror]
set_property PACKAGE_PIN B10 [get_ports {fe_data[3]}]
set_property PACKAGE_PIN B11 [get_ports fe_sessvld]
set_property PACKAGE_PIN B13 [get_ports fe_vbusvld]
set_property PACKAGE_PIN B14 [get_ports fe_xcvrsel0]
set_property PACKAGE_PIN C10 [get_ports {fe_data[0]}]
set_property PACKAGE_PIN C11 [get_ports {fe_data[4]}]
set_property PACKAGE_PIN C12 [get_ports fe_dmpd]
set_property PACKAGE_PIN C14 [get_ports fe_termsel]
set_property PACKAGE_PIN D10 [get_ports {fe_data[2]}]
set_property PACKAGE_PIN D13 [get_ports fe_txrdy]
set_property PACKAGE_PIN D14 [get_ports fe_suspendn]
set_property PACKAGE_PIN E11 [get_ports {fe_data[5]}]
set_property PACKAGE_PIN E13 [get_ports fe_txvalid]
set_property PACKAGE_PIN F11 [get_ports {fe_data[6]}]
set_property PACKAGE_PIN F13 [get_ports fe_reset]
set_property PACKAGE_PIN F14 [get_ports fe_xcvrsel1]
set_property PACKAGE_PIN G14 [get_ports fe_chrgvbus]
set_property PACKAGE_PIN H13 [get_ports fe_clk]
set_property PACKAGE_PIN H14 [get_ports fe_rxactive]
set_property PACKAGE_PIN J12 [get_ports fe_dischrgvbus]
set_property PACKAGE_PIN J13 [get_ports fe_opmode1]
set_property PACKAGE_PIN J14 [get_ports fe_opmode0]
set_property PACKAGE_PIN K11 [get_ports {fe_data[7]}]
set_property PACKAGE_PIN K12 [get_ports fe_sessend]
set_property PACKAGE_PIN L12 [get_ports fe_hostdisc]
set_property PACKAGE_PIN L13 [get_ports fe_id_dig]
set_property PACKAGE_PIN L14 [get_ports fe_idpullup]
set_property PACKAGE_PIN M11 [get_ports fe_rxvalid]
set_property PACKAGE_PIN M14 [get_ports fe_linestate1]
set_property PACKAGE_PIN N14 [get_ports fe_linestate0]

set_property PACKAGE_PIN P13 [get_ports {userio_d[0]}]
set_property PACKAGE_PIN P12 [get_ports {userio_d[1]}]
set_property PACKAGE_PIN P11 [get_ports {userio_d[3]}]
set_property PACKAGE_PIN P10 [get_ports {userio_d[5]}]
set_property PACKAGE_PIN N11 [get_ports {userio_d[4]}]
set_property PACKAGE_PIN N10 [get_ports {userio_d[6]}]
set_property PACKAGE_PIN M12 [get_ports {userio_d[2]}]
set_property PACKAGE_PIN M10 [get_ports {userio_d[7]}]
set_property PACKAGE_PIN G11 [get_ports userio_clk]

set_property PACKAGE_PIN D1 [get_ports usb_clk]
set_property PACKAGE_PIN N4 [get_ports {USB_Data[7]}]
set_property PACKAGE_PIN P5 [get_ports {USB_Data[6]}]
set_property PACKAGE_PIN B5 [get_ports {USB_Data[5]}]
set_property PACKAGE_PIN J2 [get_ports {USB_Data[4]}]
set_property PACKAGE_PIN J1 [get_ports {USB_Data[3]}]
set_property PACKAGE_PIN H3 [get_ports {USB_Data[2]}]
set_property PACKAGE_PIN A5 [get_ports {USB_Data[1]}]
set_property PACKAGE_PIN B6 [get_ports {USB_Data[0]}]

# order as per schematic:
#set_property PACKAGE_PIN J3  [get_ports USB_Addr[7] ]
#set_property PACKAGE_PIN P4  [get_ports USB_Addr[6] ]
#set_property PACKAGE_PIN P3  [get_ports USB_Addr[5] ]
#set_property PACKAGE_PIN H2  [get_ports USB_Addr[4] ]
#set_property PACKAGE_PIN H1  [get_ports USB_Addr[3] ]
#set_property PACKAGE_PIN G1  [get_ports USB_Addr[2] ]
#set_property PACKAGE_PIN L2  [get_ports USB_Addr[1] ]
#set_property PACKAGE_PIN L1  [get_ports USB_Addr[0] ]

# corrected order:
set_property PACKAGE_PIN J3 [get_ports {USB_Addr[5]}]
set_property PACKAGE_PIN P4 [get_ports {USB_Addr[4]}]
set_property PACKAGE_PIN P3 [get_ports {USB_Addr[3]}]
set_property PACKAGE_PIN H2 [get_ports {USB_Addr[2]}]
set_property PACKAGE_PIN H1 [get_ports {USB_Addr[1]}]
set_property PACKAGE_PIN G1 [get_ports {USB_Addr[0]}]
set_property PACKAGE_PIN L2 [get_ports {USB_Addr[7]}]
set_property PACKAGE_PIN L1 [get_ports {USB_Addr[6]}]

set_property PACKAGE_PIN B3 [get_ports USB_nRD]
set_property PACKAGE_PIN B2 [get_ports USB_nWE]
set_property PACKAGE_PIN A3 [get_ports USB_nCS]

set_property PACKAGE_PIN K3 [get_ports USB_SPARE0]
set_property PACKAGE_PIN A4 [get_ports USB_SPARE1]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN P2 [get_ports cw_trig]
set_property PACKAGE_PIN B1 [get_ports cw_clk]

set_property PACKAGE_PIN M13 [get_ports mcx_trig]

set_property PACKAGE_PIN D2 [get_ports LED_TRIG]
set_property PACKAGE_PIN A2 [get_ports LED_CAP]

#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets fe_clk_IBUF_BUFG]
